
- hosts: terraform-ansible
  tasks:
  - name: criar o arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1> Subiu a alteração </h1>
  - name: criar o server
    shell: "nohup busybox httpd -f -p 8080 &"