- hosts: terraform-ansible
  tasks:
    - name: instalando o python3, virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: yes

    - name: instalando dependências com pip (Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/teste/venv
        name:
          - Django
          - djangorestframework

    - name: iniciando o Projeto
      shell: '. /home/ubuntu/teste/venv/bin/activate; django-admin startproject setup /home/ubuntu/teste/'
